# Generated by Django 5.0.6 on 2024-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img',
            field=models.ImageField(default=11, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
