# Generated by Django 5.0.7 on 2024-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imges',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
